// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl23gASrCx3za9TGagFL6ct2EWHMi0vbE',
    appId: '1:202323131888:web:8e4a0530cce7dc2e4cb135',
    messagingSenderId: '202323131888',
    projectId: 'souq1-841fb',
    authDomain: 'souq1-841fb.firebaseapp.com',
    databaseURL: 'https://souq1-841fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'souq1-841fb.appspot.com',
    measurementId: 'G-Q4JT3BJW0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7BIXSgLoGxXa3TF4tPWvYFv8BFf-VIF4',
    appId: '1:202323131888:android:9bee05ebac17efb94cb135',
    messagingSenderId: '202323131888',
    projectId: 'souq1-841fb',
    databaseURL: 'https://souq1-841fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'souq1-841fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwjt1Ej76yzCrRZ_Bx8vRwMWKJxGHwUbk',
    appId: '1:202323131888:ios:894ab0cf2495a66d4cb135',
    messagingSenderId: '202323131888',
    projectId: 'souq1-841fb',
    databaseURL: 'https://souq1-841fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'souq1-841fb.appspot.com',
    androidClientId: '202323131888-6ipckr607p2f73fdq6p1jdqevtmvv9bt.apps.googleusercontent.com',
    iosClientId: '202323131888-b2p09jasb315edugpmog3rv9cbhkvlf9.apps.googleusercontent.com',
    iosBundleId: 'com.abdoanany.souq',
  );
}
